spring:
  datasource:
    url: ${DB_URL_DEV}
    username: ${DB_USER_DEV}
    password: ${DB_PASS_DEV}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
cors:
  allowed-origin: ${FRONTEND_URL:http://localhost:3838}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MY_EMAIL}
    password: ${APP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
jwt:
  secret: your-local-secret
  expiration: 86400000  # 1 day
server:
     port: ${SERVER_PORT_DEV}

