spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail: # Added for SMTP mail configuration
    host: smtp.gmail.com
    port: 587
    username: ${MY_EMAIL} # Use environment variable for production
    password: ${APP_PASSWORD} # Use environment variable for production
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 9899

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

springdoc:
  api-docs:
    enabled: true