spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vijay_works_dev
    username: devuser
    password: root
jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
profiles:
    active: dev
server:
  port: 9899
